### ISSUE TITLE
示例程序中 Vertical FlipView 的内容是横向切换的

### ISSUE THREAD

**Issue by STBBRD** [iNKORE-Public/UI.WPF.Modern#37]
**示例程序中 Vertical FlipView 的内容是横向切换的。**
玩 Gallery 时发现的，不知道其他地方有没有这个问题。

**Comment by NotYoojun** [comment]
<img width="434" alt="image" src="https://github.com/iNKORE-Public/UI.WPF.Modern/assets/54567489/0684c1ac-26a3-4443-92e6-cdc8fca11548">

这样就对了嘛
