### ISSUE TITLE
Request - being able to style a single control if no window exists.

### ISSUE THREAD

**Issue by vchelaru** [iNKORE-Public/UI.WPF.Modern#40]
**Is your feature request related to a problem? Please describe.**\
I have an application which is a Winforms application (it does not have a WPF window), so I cannot use this library because the quickstart seems to require modifying the main window.

**Describe the solution you'd like**
I have a single WPF control which hosts all other WPF controls in my project. I would like to be able to apply this styling on the wpf window and have that work on all children controls. 

**Describe alternatives you've considered**
I have tried to migrate my app to be wholly WPF but this is problematic due to the size and complexity of the app.

**Additional context**

**Comment by NotYoojun** [comment]
Does your app have a `System.Windows.Application` object?
In other words, is your `Application.Currrent` null?

**Comment by NotYoojun** [comment]
Hi there, it has been a while since the last reply of this issue. I'm afraid I have to close it right now.

If you need more help, don't hesitate to reopen this issue.
