### ISSUE TITLE
Add InputBox dialog

### ISSUE THREAD

**Issue by JeremyAnsel** [iNKORE-Public/UI.WPF.Modern#45]
**Is your feature request related to a problem? Please describe.**
Currently, to show an input box, we have to use the InputBox from the `Microsoft.VisualBasic.Interaction` class.
This requires to add a reference to `Microsoft.VisualBasic`.

**Describe the solution you'd like**
Implement a InputBox class to show a dialog asking for a string.

**Additional context**
The VB InputBox looks like that:
![image](https://github.com/iNKORE-Public/UI.WPF.Modern/assets/9573196/ddf884d5-66f8-46c6-a91e-0be376a2ca1c)

**Comment by JeremyAnsel** [comment]
@NotYoojun Thank you for this library. Do you know when the next version will be released to NuGet?

**Comment by NotYoojun** [comment]
I have approved the latest release v0.9.26, check it out!

**Comment by JeremyAnsel** [comment]
Thank you
